// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadBuilds(arg1, arg2, arg3) {
  return window['go']['lolbuild']['Loader']['LoadBuilds'](arg1, arg2, arg3);
}

export function LoadRuneTree(arg1) {
  return window['go']['lolbuild']['Loader']['LoadRuneTree'](arg1);
}
