// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {lolbuild} from '../models';

export function LoadBuilds(arg1:string,arg2:Array<string>):Promise<Array<lolbuild.BuildCollection>>;

export function LoadRuneTree(arg1:string):Promise<lolbuild.RuneTree>;
