// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChampionName(arg1, arg2) {
  return window['go']['lolbuild']['Loader']['GetChampionName'](arg1, arg2);
}

export function GetRuneTree(arg1, arg2) {
  return window['go']['lolbuild']['Loader']['GetRuneTree'](arg1, arg2);
}

export function LoadBuilds(arg1, arg2, arg3, arg4) {
  return window['go']['lolbuild']['Loader']['LoadBuilds'](arg1, arg2, arg3, arg4);
}
