// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {lolbuild} from '../models';

export function GetChampionName(arg1:number,arg2:string):Promise<lolbuild.ChampionName>;

export function GetRuneTree(arg1:string,arg2:string):Promise<lolbuild.RuneTree>;

export function LoadBuilds(arg1:string,arg2:Array<string>,arg3:string,arg4:string):Promise<Array<lolbuild.BuildCollection>>;
