// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {lcu} from '../models';

export function GetCurrentChampion():Promise<number>;

export function GetLCUState():Promise<string>;

export function GetSummoner():Promise<lcu.Summoner>;

export function Greet(arg1:string):Promise<string>;
