// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyItemSet(arg1) {
  return window['go']['main']['App']['ApplyItemSet'](arg1);
}

export function ApplyRunes(arg1) {
  return window['go']['main']['App']['ApplyRunes'](arg1);
}

export function ApplySummonerSpells(arg1, arg2) {
  return window['go']['main']['App']['ApplySummonerSpells'](arg1, arg2);
}

export function GetCurrentChampion() {
  return window['go']['main']['App']['GetCurrentChampion']();
}

export function GetGameMode() {
  return window['go']['main']['App']['GetGameMode']();
}

export function GetLCUState() {
  return window['go']['main']['App']['GetLCUState']();
}

export function GetSummoner() {
  return window['go']['main']['App']['GetSummoner']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
