// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyItemSet(arg1) {
  return window['go']['main']['App']['ApplyItemSet'](arg1);
}

export function ApplyRunes(arg1) {
  return window['go']['main']['App']['ApplyRunes'](arg1);
}

export function ApplySummonerSpells(arg1, arg2) {
  return window['go']['main']['App']['ApplySummonerSpells'](arg1, arg2);
}

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function GetAssignedRole() {
  return window['go']['main']['App']['GetAssignedRole']();
}

export function GetAutoImportSetting() {
  return window['go']['main']['App']['GetAutoImportSetting']();
}

export function GetAutoUpdateSetting() {
  return window['go']['main']['App']['GetAutoUpdateSetting']();
}

export function GetCurrentChampion() {
  return window['go']['main']['App']['GetCurrentChampion']();
}

export function GetGameMode() {
  return window['go']['main']['App']['GetGameMode']();
}

export function GetShowNativeTitleBarSetting() {
  return window['go']['main']['App']['GetShowNativeTitleBarSetting']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetSummoner() {
  return window['go']['main']['App']['GetSummoner']();
}

export function Maximize() {
  return window['go']['main']['App']['Maximize']();
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}

export function OpenLogFolder() {
  return window['go']['main']['App']['OpenLogFolder']();
}

export function SetAutoImportSetting(arg1) {
  return window['go']['main']['App']['SetAutoImportSetting'](arg1);
}

export function SetAutoUpdateSetting(arg1) {
  return window['go']['main']['App']['SetAutoUpdateSetting'](arg1);
}

export function SetShowNativeTitleBarSetting(arg1) {
  return window['go']['main']['App']['SetShowNativeTitleBarSetting'](arg1);
}
