// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLCUState() {
  return window['go']['main']['App']['GetLCUState']();
}

export function GetSummoner() {
  return window['go']['main']['App']['GetSummoner']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
