name: Release

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: geemo.exe
          build-platform: windows/amd64
          package: false
          nsis: false

      - name: Upload Artifact in GOOS-GOARCH format
        uses: actions/upload-artifact@v3
        with:
          name: windows-amd64
          path: ./build/bin/geemo.exe

  release:
    name: Release
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: windows-amd64

      - name: Zip
        run: |
          zip -r geemo-${{github.ref_name}}.zip geemo.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: geemo-${{github.ref_name}}.zip
          draft: true
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}