name: Release

on:
  push

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build (Windows)
        uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: geemo.exe
          build-platform: windows/amd64
          package: false
          nsis: false

      - name: Build (Linux)
        uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: geemo
          build-platform: linux/amd64
          package: false
          nsis: false

      - name: Upload Windows Artifact in GOOS-GOARCH format
        uses: actions/upload-artifact@v3
        with:
          name: windows-amd64
          path: ./build/bin/geemo.exe

      - name: Upload Linux Artifact in GOOS-GOARCH format
        uses: actions/upload-artifact@v3
        with:
          name: linux-amd64
          path: ./build/bin/geemo

  release:
    name: Release
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v2
        with:
          name: windows-amd64

      - name: Download Linux Artifact
        uses: actions/download-artifact@v2
        with:
          name: linux-amd64

      - name: Zip
        run: |
          zip -r geemo-windows-${{github.ref_name}}.zip geemo.exe
          zip -r geemo-linux-${{github.ref_name}}.zip geemo

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          files: |
              geemo-windows-${{github.ref_name}}.zip
              geemo-linux-${{github.ref_name}}.zip